//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler hatalı davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeklifYonetimSistemi.Services.ELogoProxy
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TeklifYonetimSistemi.Services.ELogoProxy.Application")]
    public interface Application
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.LoginResponse1> LoginAsync(TeklifYonetimSistemi.Services.ELogoProxy.Login1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.LogoutResponse1> LogoutAsync(TeklifYonetimSistemi.Services.ELogoProxy.Logout1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SendDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.SendDocumentResponse1> SendDocumentAsync(TeklifYonetimSistemi.Services.ELogoProxy.SendDocument1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentResponse1> GetDocumentAsync(TeklifYonetimSistemi.Services.ELogoProxy.GetDocument1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetDocumentDone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentDoneResponse1> GetDocumentDoneAsync(TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentDone1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="CheckGibUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.CheckGibUserResponse1> CheckGibUserAsync(TeklifYonetimSistemi.Services.ELogoProxy.CheckGibUser1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetDocumentStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentStatusResponse1> GetDocumentStatusAsync(TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentStatus1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Login
    {
        
        private LoginModel loginField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public LoginModel login
        {
            get
            {
                return this.loginField;
            }
            set
            {
                this.loginField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/eFaturaWebService")]
    public partial class LoginModel
    {
        
        private string appStrField;
        
        private string passWordField;
        
        private string sourceField;
        
        private string userNameField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string appStr
        {
            get
            {
                return this.appStrField;
            }
            set
            {
                this.appStrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string passWord
        {
            get
            {
                return this.passWordField;
            }
            set
            {
                this.passWordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=2)]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/eFaturaWebService")]
    public partial class StatusInfo
    {
        
        private string codeField;
        
        private System.Nullable<System.DateTime> currentDateField;
        
        private bool currentDateFieldSpecified;
        
        private string descriptionField;
        
        private string envelopeIdField;
        
        private System.Nullable<bool> isCancelField;
        
        private bool isCancelFieldSpecified;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> currentDate
        {
            get
            {
                return this.currentDateField;
            }
            set
            {
                this.currentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentDateSpecified
        {
            get
            {
                return this.currentDateFieldSpecified;
            }
            set
            {
                this.currentDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string envelopeId
        {
            get
            {
                return this.envelopeIdField;
            }
            set
            {
                this.envelopeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<bool> isCancel
        {
            get
            {
                return this.isCancelField;
            }
            set
            {
                this.isCancelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isCancelSpecified
        {
            get
            {
                return this.isCancelFieldSpecified;
            }
            set
            {
                this.isCancelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=5)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocumentStatusResponseModel
    {
        
        private string getDocumentStatusResultField;
        
        private string resultMsgField;
        
        private StatusInfo statusInfoField;
        
        private string elementIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string GetDocumentStatusResult
        {
            get
            {
                return this.getDocumentStatusResultField;
            }
            set
            {
                this.getDocumentStatusResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string resultMsg
        {
            get
            {
                return this.resultMsgField;
            }
            set
            {
                this.resultMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public StatusInfo statusInfo
        {
            get
            {
                return this.statusInfoField;
            }
            set
            {
                this.statusInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string elementId
        {
            get
            {
                return this.elementIdField;
            }
            set
            {
                this.elementIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocumentStatusResponse
    {
        
        private GetDocumentStatusResponseModel getDocumentStatusResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public GetDocumentStatusResponseModel GetDocumentStatusResult
        {
            get
            {
                return this.getDocumentStatusResultField;
            }
            set
            {
                this.getDocumentStatusResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocumentStatus
    {
        
        private string sessionIDField;
        
        private string uuidField;
        
        private string[] paramListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string sessionID
        {
            get
            {
                return this.sessionIDField;
            }
            set
            {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        public string[] paramList
        {
            get
            {
                return this.paramListField;
            }
            set
            {
                this.paramListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/eFaturaWebService")]
    public partial class GibUserInfoType
    {
        
        private string aliasField;
        
        private System.Nullable<System.DateTime> aliasCreationTimeField;
        
        private bool aliasCreationTimeFieldSpecified;
        
        private System.Nullable<System.DateTime> firstCreationTimeField;
        
        private bool firstCreationTimeFieldSpecified;
        
        private string identifierField;
        
        private string titleField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Alias
        {
            get
            {
                return this.aliasField;
            }
            set
            {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> AliasCreationTime
        {
            get
            {
                return this.aliasCreationTimeField;
            }
            set
            {
                this.aliasCreationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AliasCreationTimeSpecified
        {
            get
            {
                return this.aliasCreationTimeFieldSpecified;
            }
            set
            {
                this.aliasCreationTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> FirstCreationTime
        {
            get
            {
                return this.firstCreationTimeField;
            }
            set
            {
                this.firstCreationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FirstCreationTimeSpecified
        {
            get
            {
                return this.firstCreationTimeFieldSpecified;
            }
            set
            {
                this.firstCreationTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/eFaturaWebService")]
    public partial class GibUserType
    {
        
        private string despatchAdviceField;
        
        private GibUserInfoType[] despatchAdviceGbListField;
        
        private GibUserInfoType[] despatchAdvicePkListField;
        
        private string identifierField;
        
        private string invoiceField;
        
        private GibUserInfoType[] invoiceGbListField;
        
        private GibUserInfoType[] invoicePkListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string DespatchAdvice
        {
            get
            {
                return this.despatchAdviceField;
            }
            set
            {
                this.despatchAdviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DespatchAdviceGbList", IsNullable=true, Order=1)]
        public GibUserInfoType[] DespatchAdviceGbList
        {
            get
            {
                return this.despatchAdviceGbListField;
            }
            set
            {
                this.despatchAdviceGbListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DespatchAdvicePkList", IsNullable=true, Order=2)]
        public GibUserInfoType[] DespatchAdvicePkList
        {
            get
            {
                return this.despatchAdvicePkListField;
            }
            set
            {
                this.despatchAdvicePkListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=4)]
        public string Invoice
        {
            get
            {
                return this.invoiceField;
            }
            set
            {
                this.invoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InvoiceGbList", IsNullable=true, Order=5)]
        public GibUserInfoType[] InvoiceGbList
        {
            get
            {
                return this.invoiceGbListField;
            }
            set
            {
                this.invoiceGbListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InvoicePkList", IsNullable=true, Order=6)]
        public GibUserInfoType[] InvoicePkList
        {
            get
            {
                return this.invoicePkListField;
            }
            set
            {
                this.invoicePkListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckGibUserResponseModel
    {
        
        private string checkGibUserResultField;
        
        private string resultMsgField;
        
        private GibUserType[] userListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string CheckGibUserResult
        {
            get
            {
                return this.checkGibUserResultField;
            }
            set
            {
                this.checkGibUserResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string resultMsg
        {
            get
            {
                return this.resultMsgField;
            }
            set
            {
                this.resultMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/eFaturaWebService")]
        public GibUserType[] userList
        {
            get
            {
                return this.userListField;
            }
            set
            {
                this.userListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckGibUserResponse
    {
        
        private CheckGibUserResponseModel checkGibUserResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public CheckGibUserResponseModel CheckGibUserResult
        {
            get
            {
                return this.checkGibUserResultField;
            }
            set
            {
                this.checkGibUserResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckGibUser
    {
        
        private string sessionIDField;
        
        private string[] vknTcknListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string sessionID
        {
            get
            {
                return this.sessionIDField;
            }
            set
            {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        public string[] vknTcknList
        {
            get
            {
                return this.vknTcknListField;
            }
            set
            {
                this.vknTcknListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocumentDoneResponse
    {
        
        private GetDocumentResponseModel getDocumentDoneResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public GetDocumentResponseModel GetDocumentDoneResult
        {
            get
            {
                return this.getDocumentDoneResultField;
            }
            set
            {
                this.getDocumentDoneResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocumentResponseModel
    {
        
        private string getDocumentResultField;
        
        private string resultMsgField;
        
        private Document documentField;
        
        private string envelopeIdField;
        
        private string gbLabelField;
        
        private string pkLabelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string GetDocumentResult
        {
            get
            {
                return this.getDocumentResultField;
            }
            set
            {
                this.getDocumentResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string resultMsg
        {
            get
            {
                return this.resultMsgField;
            }
            set
            {
                this.resultMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public Document document
        {
            get
            {
                return this.documentField;
            }
            set
            {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string envelopeId
        {
            get
            {
                return this.envelopeIdField;
            }
            set
            {
                this.envelopeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string gbLabel
        {
            get
            {
                return this.gbLabelField;
            }
            set
            {
                this.gbLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string pkLabel
        {
            get
            {
                return this.pkLabelField;
            }
            set
            {
                this.pkLabelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/eFaturaWebService")]
    public partial class Document
    {
        
        private BinaryData binaryDataField;
        
        private System.Nullable<System.DateTime> currentDateField;
        
        private bool currentDateFieldSpecified;
        
        private string fileNameField;
        
        private string hashField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public BinaryData binaryData
        {
            get
            {
                return this.binaryDataField;
            }
            set
            {
                this.binaryDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> currentDate
        {
            get
            {
                return this.currentDateField;
            }
            set
            {
                this.currentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentDateSpecified
        {
            get
            {
                return this.currentDateFieldSpecified;
            }
            set
            {
                this.currentDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string hash
        {
            get
            {
                return this.hashField;
            }
            set
            {
                this.hashField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/eFaturaWebService")]
    public partial class BinaryData
    {
        
        private string valueField;
        
        private string contentTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string contentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocumentDone
    {
        
        private string sessionIDField;
        
        private string uuidField;
        
        private string[] paramListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string sessionID
        {
            get
            {
                return this.sessionIDField;
            }
            set
            {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        public string[] paramList
        {
            get
            {
                return this.paramListField;
            }
            set
            {
                this.paramListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocumentResponse
    {
        
        private GetDocumentResponseModel getDocumentResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public GetDocumentResponseModel GetDocumentResult
        {
            get
            {
                return this.getDocumentResultField;
            }
            set
            {
                this.getDocumentResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocument
    {
        
        private string sessionIDField;
        
        private string[] paramListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string sessionID
        {
            get
            {
                return this.sessionIDField;
            }
            set
            {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        public string[] paramList
        {
            get
            {
                return this.paramListField;
            }
            set
            {
                this.paramListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SendDocumentResponseModel
    {
        
        private string resultCodeField;
        
        private string resultMsgField;
        
        private string refIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string resultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string resultMsg
        {
            get
            {
                return this.resultMsgField;
            }
            set
            {
                this.resultMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=2)]
        public string refId
        {
            get
            {
                return this.refIdField;
            }
            set
            {
                this.refIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SendDocumentResponse
    {
        
        private SendDocumentResponseModel sendDocumentResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public SendDocumentResponseModel SendDocumentResult
        {
            get
            {
                return this.sendDocumentResultField;
            }
            set
            {
                this.sendDocumentResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SendDocument
    {
        
        private string sessionIDField;
        
        private string[] paramListField;
        
        private Document documentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string sessionID
        {
            get
            {
                return this.sessionIDField;
            }
            set
            {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        public string[] paramList
        {
            get
            {
                return this.paramListField;
            }
            set
            {
                this.paramListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public Document document
        {
            get
            {
                return this.documentField;
            }
            set
            {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutResponse
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Logout
    {
        
        private string sessionIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string sessionID
        {
            get
            {
                return this.sessionIDField;
            }
            set
            {
                this.sessionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseModel
    {
        
        private System.Nullable<bool> loginResultField;
        
        private bool loginResultFieldSpecified;
        
        private string sessionIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<bool> LoginResult
        {
            get
            {
                return this.loginResultField;
            }
            set
            {
                this.loginResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LoginResultSpecified
        {
            get
            {
                return this.loginResultFieldSpecified;
            }
            set
            {
                this.loginResultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string sessionID
        {
            get
            {
                return this.sessionIDField;
            }
            set
            {
                this.sessionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponse
    {
        
        private LoginResponseModel loginResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public LoginResponseModel LoginResult
        {
            get
            {
                return this.loginResultField;
            }
            set
            {
                this.loginResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Login1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TeklifYonetimSistemi.Services.ELogoProxy.Login Login;
        
        public Login1()
        {
        }
        
        public Login1(TeklifYonetimSistemi.Services.ELogoProxy.Login Login)
        {
            this.Login = Login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TeklifYonetimSistemi.Services.ELogoProxy.LoginResponse LoginResponse;
        
        public LoginResponse1()
        {
        }
        
        public LoginResponse1(TeklifYonetimSistemi.Services.ELogoProxy.LoginResponse LoginResponse)
        {
            this.LoginResponse = LoginResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Logout1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TeklifYonetimSistemi.Services.ELogoProxy.Logout Logout;
        
        public Logout1()
        {
        }
        
        public Logout1(TeklifYonetimSistemi.Services.ELogoProxy.Logout Logout)
        {
            this.Logout = Logout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TeklifYonetimSistemi.Services.ELogoProxy.LogoutResponse LogoutResponse;
        
        public LogoutResponse1()
        {
        }
        
        public LogoutResponse1(TeklifYonetimSistemi.Services.ELogoProxy.LogoutResponse LogoutResponse)
        {
            this.LogoutResponse = LogoutResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendDocument1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TeklifYonetimSistemi.Services.ELogoProxy.SendDocument SendDocument;
        
        public SendDocument1()
        {
        }
        
        public SendDocument1(TeklifYonetimSistemi.Services.ELogoProxy.SendDocument SendDocument)
        {
            this.SendDocument = SendDocument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendDocumentResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TeklifYonetimSistemi.Services.ELogoProxy.SendDocumentResponse SendDocumentResponse;
        
        public SendDocumentResponse1()
        {
        }
        
        public SendDocumentResponse1(TeklifYonetimSistemi.Services.ELogoProxy.SendDocumentResponse SendDocumentResponse)
        {
            this.SendDocumentResponse = SendDocumentResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocument1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TeklifYonetimSistemi.Services.ELogoProxy.GetDocument GetDocument;
        
        public GetDocument1()
        {
        }
        
        public GetDocument1(TeklifYonetimSistemi.Services.ELogoProxy.GetDocument GetDocument)
        {
            this.GetDocument = GetDocument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentResponse GetDocumentResponse;
        
        public GetDocumentResponse1()
        {
        }
        
        public GetDocumentResponse1(TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentResponse GetDocumentResponse)
        {
            this.GetDocumentResponse = GetDocumentResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentDone1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentDone GetDocumentDone;
        
        public GetDocumentDone1()
        {
        }
        
        public GetDocumentDone1(TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentDone GetDocumentDone)
        {
            this.GetDocumentDone = GetDocumentDone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentDoneResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentDoneResponse GetDocumentDoneResponse;
        
        public GetDocumentDoneResponse1()
        {
        }
        
        public GetDocumentDoneResponse1(TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentDoneResponse GetDocumentDoneResponse)
        {
            this.GetDocumentDoneResponse = GetDocumentDoneResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckGibUser1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TeklifYonetimSistemi.Services.ELogoProxy.CheckGibUser CheckGibUser;
        
        public CheckGibUser1()
        {
        }
        
        public CheckGibUser1(TeklifYonetimSistemi.Services.ELogoProxy.CheckGibUser CheckGibUser)
        {
            this.CheckGibUser = CheckGibUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckGibUserResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TeklifYonetimSistemi.Services.ELogoProxy.CheckGibUserResponse CheckGibUserResponse;
        
        public CheckGibUserResponse1()
        {
        }
        
        public CheckGibUserResponse1(TeklifYonetimSistemi.Services.ELogoProxy.CheckGibUserResponse CheckGibUserResponse)
        {
            this.CheckGibUserResponse = CheckGibUserResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentStatus1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentStatus GetDocumentStatus;
        
        public GetDocumentStatus1()
        {
        }
        
        public GetDocumentStatus1(TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentStatus GetDocumentStatus)
        {
            this.GetDocumentStatus = GetDocumentStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentStatusResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentStatusResponse GetDocumentStatusResponse;
        
        public GetDocumentStatusResponse1()
        {
        }
        
        public GetDocumentStatusResponse1(TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentStatusResponse GetDocumentStatusResponse)
        {
            this.GetDocumentStatusResponse = GetDocumentStatusResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ApplicationChannel : TeklifYonetimSistemi.Services.ELogoProxy.Application, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ApplicationClient : System.ServiceModel.ClientBase<TeklifYonetimSistemi.Services.ELogoProxy.Application>, TeklifYonetimSistemi.Services.ELogoProxy.Application
    {
        
        /// <summary>
        /// Hizmet uç noktasını yapılandırmak için bu kısmi metodu uygulayın.
        /// </summary>
        /// <param name="serviceEndpoint">Yapılandırılacak uç nokta</param>
        /// <param name="clientCredentials">İstemci kimlik bilgileri</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ApplicationClient() : 
                base(ApplicationClient.GetDefaultBinding(), ApplicationClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Application.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(EndpointConfiguration endpointConfiguration) : 
                base(ApplicationClient.GetBindingForEndpoint(endpointConfiguration), ApplicationClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ApplicationClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ApplicationClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.LoginResponse1> TeklifYonetimSistemi.Services.ELogoProxy.Application.LoginAsync(TeklifYonetimSistemi.Services.ELogoProxy.Login1 request)
        {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.LoginResponse1> LoginAsync(TeklifYonetimSistemi.Services.ELogoProxy.Login Login)
        {
            TeklifYonetimSistemi.Services.ELogoProxy.Login1 inValue = new TeklifYonetimSistemi.Services.ELogoProxy.Login1();
            inValue.Login = Login;
            return ((TeklifYonetimSistemi.Services.ELogoProxy.Application)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.LogoutResponse1> TeklifYonetimSistemi.Services.ELogoProxy.Application.LogoutAsync(TeklifYonetimSistemi.Services.ELogoProxy.Logout1 request)
        {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.LogoutResponse1> LogoutAsync(TeklifYonetimSistemi.Services.ELogoProxy.Logout Logout)
        {
            TeklifYonetimSistemi.Services.ELogoProxy.Logout1 inValue = new TeklifYonetimSistemi.Services.ELogoProxy.Logout1();
            inValue.Logout = Logout;
            return ((TeklifYonetimSistemi.Services.ELogoProxy.Application)(this)).LogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.SendDocumentResponse1> TeklifYonetimSistemi.Services.ELogoProxy.Application.SendDocumentAsync(TeklifYonetimSistemi.Services.ELogoProxy.SendDocument1 request)
        {
            return base.Channel.SendDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.SendDocumentResponse1> SendDocumentAsync(TeklifYonetimSistemi.Services.ELogoProxy.SendDocument SendDocument)
        {
            TeklifYonetimSistemi.Services.ELogoProxy.SendDocument1 inValue = new TeklifYonetimSistemi.Services.ELogoProxy.SendDocument1();
            inValue.SendDocument = SendDocument;
            return ((TeklifYonetimSistemi.Services.ELogoProxy.Application)(this)).SendDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentResponse1> TeklifYonetimSistemi.Services.ELogoProxy.Application.GetDocumentAsync(TeklifYonetimSistemi.Services.ELogoProxy.GetDocument1 request)
        {
            return base.Channel.GetDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentResponse1> GetDocumentAsync(TeklifYonetimSistemi.Services.ELogoProxy.GetDocument GetDocument)
        {
            TeklifYonetimSistemi.Services.ELogoProxy.GetDocument1 inValue = new TeklifYonetimSistemi.Services.ELogoProxy.GetDocument1();
            inValue.GetDocument = GetDocument;
            return ((TeklifYonetimSistemi.Services.ELogoProxy.Application)(this)).GetDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentDoneResponse1> TeklifYonetimSistemi.Services.ELogoProxy.Application.GetDocumentDoneAsync(TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentDone1 request)
        {
            return base.Channel.GetDocumentDoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentDoneResponse1> GetDocumentDoneAsync(TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentDone GetDocumentDone)
        {
            TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentDone1 inValue = new TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentDone1();
            inValue.GetDocumentDone = GetDocumentDone;
            return ((TeklifYonetimSistemi.Services.ELogoProxy.Application)(this)).GetDocumentDoneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.CheckGibUserResponse1> TeklifYonetimSistemi.Services.ELogoProxy.Application.CheckGibUserAsync(TeklifYonetimSistemi.Services.ELogoProxy.CheckGibUser1 request)
        {
            return base.Channel.CheckGibUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.CheckGibUserResponse1> CheckGibUserAsync(TeklifYonetimSistemi.Services.ELogoProxy.CheckGibUser CheckGibUser)
        {
            TeklifYonetimSistemi.Services.ELogoProxy.CheckGibUser1 inValue = new TeklifYonetimSistemi.Services.ELogoProxy.CheckGibUser1();
            inValue.CheckGibUser = CheckGibUser;
            return ((TeklifYonetimSistemi.Services.ELogoProxy.Application)(this)).CheckGibUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentStatusResponse1> TeklifYonetimSistemi.Services.ELogoProxy.Application.GetDocumentStatusAsync(TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentStatus1 request)
        {
            return base.Channel.GetDocumentStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentStatusResponse1> GetDocumentStatusAsync(TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentStatus GetDocumentStatus)
        {
            TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentStatus1 inValue = new TeklifYonetimSistemi.Services.ELogoProxy.GetDocumentStatus1();
            inValue.GetDocumentStatus = GetDocumentStatus;
            return ((TeklifYonetimSistemi.Services.ELogoProxy.Application)(this)).GetDocumentStatusAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Application))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("\'{0}\' adlı uç nokta bulunamadı.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Application))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/");
            }
            throw new System.InvalidOperationException(string.Format("\'{0}\' adlı uç nokta bulunamadı.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ApplicationClient.GetBindingForEndpoint(EndpointConfiguration.Application);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ApplicationClient.GetEndpointAddress(EndpointConfiguration.Application);
        }
        
        public enum EndpointConfiguration
        {
            
            Application,
        }
    }
}
